### ISSUE TITLE
Variables are bleeding to the global scope when testing

### ISSUE THREAD

**Issue by bezformy** [geckoboard/geckoboard-node#9]
For example here because the previous line ends with a `;` (and not `,`) which closes the variable definition part:
https://github.com/geckoboard/geckoboard-node/blob/f7e2413150175b0a460fcc63647424f8a9ce5eb3/lib/index-test.js#L3
https://github.com/geckoboard/geckoboard-node/blob/f7e2413150175b0a460fcc63647424f8a9ce5eb3/lib/datasets-test.js#L63
https://github.com/geckoboard/geckoboard-node/blob/f7e2413150175b0a460fcc63647424f8a9ce5eb3/lib/find-or-create-test.js#L11-L21
https://github.com/geckoboard/geckoboard-node/blob/f7e2413150175b0a460fcc63647424f8a9ce5eb3/lib/ping-test.js#L9

Here because of missing `var`, `let`, or `const`:
https://github.com/geckoboard/geckoboard-node/blob/f7e2413150175b0a460fcc63647424f8a9ce5eb3/lib/api-request-test.js#L11
https://github.com/geckoboard/geckoboard-node/blob/f7e2413150175b0a460fcc63647424f8a9ce5eb3/lib/api-request-test.js#L28

**Comment by carlmw** [comment]
👍  thanks for this. I've added ESlint and spent a little time tidying things up https://github.com/geckoboard/geckoboard-node/pull/13
